# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9f6999079bbc41387dd3004f64c8c45f1f935d14a7afe4b8077f41c17d6fb00e2015852e00162c8abc3a5ea7eeb1a36ce811cdf0f16b4df90ac3eae0288806

test:
  secret_key_base: 9fc4f21a481f77615b7892bfc35aa58ac5ee104142272107a1d4d6a6223697234630745d0ad44270cdd61ecc8d5c581d8c91bd059d2176a653001d9e33c1672e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
